---
title: "analysis"
output: html_document
---

```{r}
library(readr)
library(leaps)
library(DAAG)
```

```{r}
fullData = read_csv("fulldata.csv")
```

```{r}
fullSet = fullData %>% 
  group_by(hour,day) %>% 
  summarize(pickups = n())
View(fullSet)
```

```{r}
Y<-fullData %>% 
  group_by(day,hour) %>% 
  summarize(pickup = n(),Humidity,temperature,pressure,windspeed,Lat,Lon,day,boroughCode) %>%
  mutate(hours = as.double(hour)) %>% 
  ungroup %>% 
  transmute(pickup, Lat,Lon,hours,windspeed,pressure,temperature,Humidity,day,boroughCode)
Y
lin<-lm(pickup~.,data = Y)
summary(lin)
```


```{r}
myLeaps<- regsubsets(pickup~.,data = Y,nbest = 9)
  (myLeaps.summary<- summary(myLeaps))

bettertable<- cbind(myLeaps.summary$which,
                    myLeaps.summary$rsq, myLeaps.summary$rss,
                    myLeaps.summary$adjr2,myLeaps.summary$cp, myLeaps.summary$bic)
dimnames(bettertable)[[2]]<- c(dimnames(myLeaps.summary$which)[[2]],
                               "R2","SSE","R2_(adj)","cp","BIC")
bettertable=round(bettertable,3)
bettertable
n=dim(Y)[1]
fit0<- lm(pickup~1, data=Y)
fitall<- lm(pickup~., data=Y)
```


```{r}
m1<-step(fit0,fitall,direction = "forward", k=log(n))
summary(m1)
m2<-step(fitall,direction="backward",k=log(n))
summary(m2)
m3<-step(fitall,direction="both",k=log(n))
summary(m3)
```


```{r}
m1<- "pickup~Humidity+temperature+pressure"
m2<- "pickup~1"
model1cv=CVlm(data = Y, form.lm = formula(m1), m=8, seed=7,plotit=F)
model2cv=CVlm(data = Y, form.lm = formula(m2),m=8,seed=7,plotit = F)
```

# PCA first check for multicollinearity
```{r}
pairs(Y)
library(olsrr)

model1 = lm(pickup~.,data = Y)
summary(model1)
ols_vif_tol(model1)

ols_eigen_cindex(model1)

ols_coll_diag(model1)

library(pls)
pcr_model = pcr(pickup~., data = Y, scale = T, center = T, validation = "CV")
summary(pcr_model)

par(mfrow=c(1,3))
validationplot(pcr_model)
validationplot(pcr_model, val.type = "MSEP")
validationplot(pcr_model, val.type = "R2")

y_model = pcr(pickup~., data = Y, scale = T, center =T, ncomp =7)

names(y_model)

Beta = coef(y_model,ncomp = 7, intercept = T)
Beta

y_model$fitted.values
y_fitted = y_model$fitted.values[,,7]
y_fitted = y_model$residuals[,,7]

R2 = (cor(y_fitted,Y$pickup))^2
R2
```


```{r}
fullData<- fullData %>% 
  mutate(boroughCode = as.double(boroughCode)) %>% 
  mutate(hour = as.double(hour)) %>% 
  mutate(minute = as.double(minute)) %>% 
  mutate(month = as.double(month)) %>% 
  mutate(day = as.double(day)) %>% 
  group_by(hour) %>% 
  mutate(pickup = n()) %>% 
  mutate(pickup = as.double(pickup))
fullData
byNeighborhood<- fullData %>% 
  group_by(neighborhood)
byNeighborhood
```
