---
title: "CaitlinAnalysis"
author: "Caitlin Bolz"
date: "4/28/2021"
output: html_document
---

```{r message=FALSE}
library(readr)
library(leaps)
library(DAAG)
library(recipes)
library(stringr)
library(tidytext)
library(ggplot2)
library(ggrepel)
```

```{r message=FALSE}
fullData = read_csv("fulldata.csv")
```

# Formatting data
```{r}
Y<-fullData %>% 
  group_by(day, hour) %>% 
  summarize(pickup = n(), windspeed, pressure, temperature, Humidity, Lat, Lon, boroughCode) %>%
  mutate(hours = as.double(hour)) %>% 
  ungroup %>% 
  transmute(hour, day, pickup, windspeed, pressure, temperature, Humidity, Lat, Lon, boroughCode)
```

# Linear Model
```{r}
lin<-lm(pickup~.,data = Y)
summary(lin)
```

# PCA
```{r}
pca_rep = recipe(pickup~., data = Y) %>% 
  update_role(day, hour, new_role = "id") %>% 
  step_normalize(all_predictors()) %>% 
  step_pca(all_predictors())

pca_prep = prep(pca_rep)

components = tidy(pca_prep, 2)
scores = juice(pca_prep)
variances = tidy(pca_prep, 2, type = "variance")

components = components %>%
  filter(component %in% str_c("PC", 1:6)) %>% 
  mutate(terms = reorder_within(terms, abs(value), component))
```

## plot of variance
```{r}
variances = variances %>% filter(terms == "percent variance")
ggplot(variances) +  geom_col(aes(component, value))
```

## plot of top 6 components
```{r}
ggplot(components, aes(value, terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ component, scales = "free_y") +
  scale_y_reordered() +
  labs(y = NULL) +
  theme(axis.text = element_text(size = 10), strip.text = element_text(size = 10))
```

# scores, not the best graph
```{r}
ggplot(scores, aes(PC1, PC2, label = hour)) +
  geom_point(aes(color = hour), alpha = 0.5, size = .5) +
  scale_color_viridis_c()
```

```{r}
ggplot(scores, aes(PC3, PC4, label = hour)) +
  geom_point(aes(color = hour), alpha = 0.5, size = .5) +
  scale_color_viridis_c()
```

```{r}
ggplot(scores, aes(PC2, PC4, label = hour)) +
  geom_point(aes(color = hour), alpha = 0.5, size = .5) +
  scale_color_viridis_c()
```

```{r}
ggplot(scores, aes(PC3, PC5, label = hour)) +
  geom_point(aes(color = hour), alpha = 0.5, size = .5) +
  scale_color_viridis_c()
```
