---
title: "Uber"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(readr)
library(tidyverse)
library(leaps)
library(DAAG)
library(recipes)
library(stringr)
library(tidytext)
library(ggplot2)
library(ggrepel)
library(lubridate)
library(sp)
library(tigris)
library(dplyr)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
library(rgdal)
```


```{r message=FALSE}
may<-read_csv("uber-raw-data-may14.csv")
cleanmay = may %>% 
  separate("Date/Time", into =c("Date","Time"), sep= " ") %>% 
  mutate(dayOfWeek = Date) %>% 
  mutate(dayOfWeek = mdy(Date)) %>% 
  mutate(dayOfWeek = wday(dayOfWeek)) %>% 
  separate(Date, into = c("month","day","year"),sep="/") %>% 
  separate(Time, into = c("hour", "minute"),sep=":")
cleanmay
```

Reading in weather
```{r message=FALSE, warning=FALSE}
hum<-read_csv("humidity.csv")
Humidityin2014<-hum %>% 
  separate("datetime", into = c("Date","hour"), sep = " ") %>% 
  separate("Date", into = c("month","day","year"),sep="/") %>% 
  filter(year==14) %>% 
  mutate(Humidity = `New York`) %>% 
  transmute(hour,day,month,year,Humidity)
Sky<-read_csv("weather_description.csv")
JustNewYorkSky<-Sky %>% 
  separate("datetime", into = c("Date","hour"), sep = " ") %>% 
  separate("Date", into = c("month","day","year"), sep="/") %>% 
  filter(year==14) %>% 
  mutate(SkyDescription=`New York`) %>% 
  transmute(hour,day,month,year,SkyDescription)
temp<-read_csv("temperature.csv")
JustTemp<-temp %>% 
  separate("datetime", into = c("Date","hour"), sep=" ") %>% 
  separate("Date", into = c("month","day","year"),sep="/") %>% 
  filter(year==14) %>% 
  transmute(hour,day,month,year,`New York`) %>% 
  mutate(temperature=((`New York`-273.15)*9/5)+32) %>% 
  transmute(hour,day,month,year,temperature)
pre<- read_csv("pressure.csv")
pressur<- pre %>% 
  separate("datetime", into = c("Date","hour"), sep = " ") %>% 
  separate("Date", into = c("month","day","year"), sep="/") %>% 
  filter(year==14) %>% 
  mutate(pressure=`New York`) %>% 
  transmute(hour,day,month,year,pressure)
win<- read_csv("wind_speed.csv")
win<- win %>% 
  separate("datetime", into = c("Date","hour"), sep = " ") %>% 
  separate("Date", into = c("month","day","year"), sep="/") %>% 
  filter(year==14) %>% 
  mutate(windspeed=`New York`) %>% 
  transmute(hour,day,month,year,windspeed)
d<-full_join(Humidityin2014,JustNewYorkSky)
temporary<- full_join(win,pressur) %>% 
  full_join(d)
weatherData<-full_join(temporary,JustTemp) %>% 
  separate(hour,into = c("hour"),sep = ":")
weatherData<- weatherData %>%  
  transmute(hour,day,month,windspeed,pressure,Humidity,SkyDescription,temperature)

weather =weatherData %>% 
  filter(month==5) %>% 
  transmute(hour,day,temperature,pressure,windspeed,Humidity) %>% 
  mutate(hour = as.double(hour)) %>% 
  mutate(day = as.double(day))
```

Uber and Weather together
```{r warning=FALSE}
UberandWeather <- cleanmay %>% 
  full_join(weatherData) 
UberandWeather <- subset(UberandWeather, select = c("hour", "minute", "Lat", "Lon", "month", "day", "Humidity", "SkyDescription", "temperature", "pressure","windspeed","dayOfWeek"))
UberandWeather <- na.omit(UberandWeather)
```

```{r}
r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)
uw = UberandWeather
lats <- uw$Lat
lngs <- uw$Lon
points <- data.frame(lat=lats, lng=lngs)
points_spdf <- points
coordinates(points_spdf) <- ~lng + lat
proj4string(points_spdf) <- proj4string(nyc_neighborhoods)
matches <- over(points_spdf, nyc_neighborhoods)
points <- cbind(points, matches)
points$Lat = points$lat
points$Lon = points$lng
fullData = points %>% 
  left_join(uw)
fullData = distinct(fullData)
fullData = fullData %>% 
  transmute(Lat,Lon,neighborhood,boroughCode,borough,month,day,hour,minute,dayOfWeek,
            windspeed,pressure,Humidity,SkyDescription,temperature)
```

# figure 1
```{r}
sum<-UberandWeather %>%
  filter(month == 5) %>% 
  group_by(day) %>% 
  summarize(pickup=n(), temp = mean(temperature))
sum$day = as.numeric(sum$day)
ggplot(sum, aes(x = day, y = pickup, fill = temp)) +
  geom_col() +
  scale_fill_gradient(low = "white", high = "red") +
  labs(
    title = "Number of Uber Pickups in NYC in May 2014",
    x = "Day of the Month",
    y = "Number of Pickups",
    fill = "Temperature") +
  scale_x_continuous(breaks = waiver(), n.breaks = 6)
```


# New dataframes
```{r}
fullData = fullData %>%
  mutate( 
    borough = case_when(
      str_detect(borough, "Brooklyn") ~ paste("Kings"),
      str_detect(borough, "Manhattan") ~ paste("New York"),
      str_detect(borough, "Staten Island") ~ paste("Richmond"),
      str_detect(borough, "Queens") ~ paste("Queens"),
      str_detect(borough, "Bronx") ~ paste("Bronx")))

tab = fullData %>% 
  transmute(borough, neighborhood, day,neighborhood) %>% 
  na.omit(borough) %>% 
  group_by(day,borough) %>% 
  summarize(num_pickups = n()) %>% 
  pivot_wider(names_from = borough, values_from = num_pickups)
tab
```

# Formatting data
```{r}
Yhat = fullData %>% 
  na.omit(boroughCode) %>% 
  group_by(boroughCode,hour,day,dayOfWeek) %>% 
  summarize(pickup = n()) %>% 
  mutate(hour = as.double(hour)) %>% 
  mutate(day = as.double(day)) 

# do the join separate
Ytilda = Yhat %>% full_join(weather) %>% mutate(boroughCode=as.double(boroughCode)) %>% 
  mutate(pickup = as.double(pickup)) %>% na.omit(Yhat) %>% 
  ungroup
Ytilda
```


# data for app
```{r}
Yapp = fullData %>% 
  na.omit(boroughCode) %>% 
  group_by(borough,hour,day,dayOfWeek) %>% 
  summarize(pickup = n()) %>% 
  mutate(hour = as.double(hour)) %>% 
  mutate(day = as.double(day)) 

Yapp1 = Yapp %>% 
  filter(day == 1 | day == 2 | day == 3) %>% 
  group_by(borough) %>% 
  summarize(pickups = sum(pickup))

Yapp2 = Yapp %>% 
  filter(day == 4 | day == 5 | day == 6 | day == 7 | day == 8 | day == 9 | day == 10) %>% 
  group_by(borough) %>% 
  summarize(pickups = sum(pickup))

Yapp3 = Yapp %>% 
  filter(day == 11 | day == 12 | day == 13 | day == 14 | day == 15 | day == 16 | day == 17) %>% 
  group_by(borough) %>% 
  summarize(pickups = sum(pickup))

Yapp4 = Yapp %>% 
  filter(day == 18 | day == 19 | day == 20 | day == 21 | day == 22 | day == 23 | day == 24) %>% 
  group_by(borough) %>% 
  summarize(pickups = sum(pickup))

Yapp5 = Yapp %>% 
  filter(day == 25 | day == 26 | day == 27 | day == 28 | day == 29 | day == 30 | day == 31) %>% 
  group_by(borough) %>% 
  summarize(pickups = sum(pickup))
```


```{r}
borough = c("Manhattan","Brooklyn","Queens","Bronx","Staten Island")

# Get lat/long coordinates for NY counties
choropleth = map_data("county") %>% 
  filter(region == "new york") %>% 
  select(-group, -order, - region) %>% 
  rename(County = subregion) %>% 
  mutate(County = str_to_title(County)) %>% 
  filter(County == "New York" | County == "Kings" | County == "Queens" | 
           County == "Bronx" | County == "Richmond") %>% 
  rename(borough = County)
```


```{r}
choropleth1 = choropleth %>% 
  left_join(Yapp1, by = c("borough"))

choropleth2 = choropleth %>% 
  left_join(Yapp2, by = c("borough"))

choropleth3 = choropleth %>% 
  left_join(Yapp3, by = c("borough"))

choropleth4 = choropleth %>% 
  left_join(Yapp4, by = c("borough"))

choropleth5 = choropleth %>% 
  left_join(Yapp5, by = c("borough"))
```

```{r}
write_csv(choropleth1, "choropleth1.csv")
write_csv(choropleth2, "choropleth2.csv")
write_csv(choropleth3, "choropleth3.csv")
write_csv(choropleth4, "choropleth4.csv")
write_csv(choropleth5, "choropleth5.csv")
```


#figure 2
```{r}
library(ggplot2)
ggplot(data = Ytilda, mapping = aes(x =hour, y = pickup))+geom_point(mapping = aes(color = day))+facet_wrap(~boroughCode)
```

# Linear Model
```{r}
lin<-lm(pickup~.,data = Ytilda)
summary(lin)
```

# PCA
```{r}
pca_rep = recipe(pickup~., data = Ytilda) %>% 
  update_role(day, hour, new_role = "id") %>% 
  step_normalize(all_predictors()) %>% 
  step_pca(all_predictors())

pca_prep = prep(pca_rep)

components = tidy(pca_prep, 2)
scores = juice(pca_prep)
variances = tidy(pca_prep, 2, type = "variance")

components = components %>%
  filter(component %in% str_c("PC", 1:6)) %>% 
  mutate(terms = reorder_within(terms, abs(value), component))
```

## plot of variance
```{r}
variances = variances %>% filter(terms == "percent variance")
ggplot(variances) +  geom_col(aes(component, value))
```

## plot of top 6 components
```{r}
ggplot(components, aes(value, terms)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ component, scales = "free_y") +
  scale_y_reordered() +
  labs(y = NULL) +
  theme(axis.text = element_text(size = 10), strip.text = element_text(size = 10))
```

## scores, not the best graphs
```{r}
ggplot(scores, aes(PC1, PC2, label = hour)) +
  geom_point(aes(color = hour), alpha = 1, size = 1) +
  scale_color_viridis_c()

ggplot(scores, aes(PC3, PC4, label = hour)) +
  geom_point(aes(color = hour), alpha = 1, size = 1) +
  scale_color_viridis_c()

ggplot(scores, aes(PC2, PC4, label = hour)) +
  geom_point(aes(color = hour), alpha = 1, size = 1) +
  scale_color_viridis_c()

ggplot(scores, aes(PC3, PC5, label = hour)) +
  geom_point(aes(color = hour), alpha = 1, size = 1) +
  scale_color_viridis_c()
```

# matt's analysis
```{r}
library(olsrr)
model1 = lm(pickup~., data = Ytilda)
summary(model1)

ols_vif_tol(model1)
ols_eigen_cindex(model1)
ols_coll_diag(model1)

library(pls)
pcr_model = pcr(pickup~., data = Ytilda, scale = T, center = T, validation = "CV")
summary(pcr_model)

par(mfrow=c(1,3))
validationplot(pcr_model)
validationplot(pcr_model, val.type="MSEP")
validationplot(pcr_model, val.type = "R2")

uber_model = pcr(pickup~., data = Ytilda, scale = T, center = T, ncomp = 5)
 names(uber_model)
Beta = coef(uber_model,ncomp = 5, intercept = T)
Beta
```

# matt you had this in uber.rmd
```{r}
library(plotly)
library(rjson)
r1 = 'http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson'
geojson <- rjson::fromJSON(file=r1)
full = fullData %>% 
  transmute(borough,neighborhood,day) %>% 
  group_by(borough,day,neighborhood) %>% 
  summarize(num_points= n(),borough,day)
full = distinct(full)
full
fig <- plot_ly() 
fig <- fig %>% add_trace(
  type="choroplethmapbox",
  geojson=geojson,
  locations=full$neighborhood,
  z=full$num_points,
  colorscale="Viridis",
  featureidkey = "properties.neighborhood"
)
fig <- fig %>% layout(
  mapbox=list(
    style="carto-positron",
    zoom =9,
    center=list(lon = -73.98,lat =  40.75))
)
fig

```



# write stuff needed for app at the end here
```{r}

wrtie_csv(fullData, "FullData.csv")
```





